export const webFrontend = [
  "coffeescript",
  "csp",
  "css",
  "css-extras",
  "flow",
  "graphql",
  "haml",
  "handlebars",
  "javascript",
  "json",
  "jsx",
  "less",
  "liquid",
  "livescript",
  "markup",
  "markup-templating",
  "n4js",
  "pug",
  "sass",
  "scss",
  "smarty",
  "soy",
  "stylus",
  "tsx",
  "twig",
  "typescript",
  "velocity",
];

export const backendGeneral = [
  "abap",
  "aspnet",
  "basic",
  "crystal",
  "csharp",
  "d",
  "django",
  "eiffel",
  "erb",
  "go",
  "groovy",
  "haxe",
  "java",
  "lua",
  "nim",
  "pascal",
  "perl",
  "php",
  "php-extras",
  "python",
  "ruby",
  "rust",
  "scala",
  "smalltalk",
  "tcl",
  "vbnet",
  "visual-basic",
  "xojo",
];

export const systemsLowLevel = [
  "ada",
  "arduino",
  "asm6502",
  "c",
  "clike",
  "cpp",
  "fortran",
  "glsl",
  "nasm",
  "opencl",
  "verilog",
  "vhdl",
  "wasm",
];

export const mobileDevelopment = [
  "actionscript",
  "dart",
  "kotlin",
  "monkey",
  "objectivec",
  "swift",
];

export const dataScienceMath = [
  "apl",
  "arff",
  "julia",
  "matlab",
  "mizar",
  "parigp",
  "prolog",
  "q",
  "r",
  "sas",
];

export const functionalProgramming = [
  "clojure",
  "elixir",
  "elm",
  "erlang",
  "fsharp",
  "haskell",
  "io",
  "lisp",
  "ocaml",
  "oz",
  "pure",
  "reason",
  "scheme",
];

export const databaseQuery = ["plsql", "sql", "xquery"];

export const devOpsConfig = [
  "apacheconf",
  "docker",
  "git",
  "hpkp",
  "hsts",
  "http",
  "ini",
  "makefile",
  "nginx",
  "nix",
  "properties",
  "protobuf",
  "puppet",
  "roboconf",
  "yaml",
];

export const shellAutomation = [
  "applescript",
  "autohotkey",
  "autoit",
  "bash",
  "batch",
  "nsis",
  "powershell",
  "vim",
];

export const markupDocs = [
  "asciidoc",
  "diff",
  "gedcom",
  "gherkin",
  "latex",
  "markdown",
  "rest",
  "textile",
  "wiki",
];

export const miscellaneous = [
  "bison",
  "brainfuck",
  "bro",
  "gml",
  "ichigojam",
  "icon",
  "inform7",
  "j",
  "jolie",
  "keyman",
  "lolcode",
  "mel",
  "parser",
  "processing",
  "qore",
  "renpy",
  "rip",
  "tap",
  "tt2",
  "xeora",
];

//! The important one, but exported
export const allLanguages: Map<string, [string, string[]]> = new Map([
  ["backendGeneral", ["Backend", backendGeneral]],
  ["databaseQuery", ["Database", databaseQuery]],
  ["dataScienceMath", ["Data Science & Math", dataScienceMath]],
  ["devOpsConfig", ["DevOps/Config", devOpsConfig]],
  ["functionalProgramming", ["Functional Programming", functionalProgramming]],
  ["markupDocs", ["Markup & Docs", markupDocs]],
  ["mobileDevelopment", ["Mobile Development", mobileDevelopment]],
  ["shellAutomation", ["Shell & Automation", shellAutomation]],
  ["systemsLowLevel", ["Systems & Low Level", systemsLowLevel]],
  ["webFrontend", ["Web Development", webFrontend]],
  ["miscellaneous", ["Miscellaneous", miscellaneous]],
]);

export const allLanguagesFlat = Array.from(allLanguages.values()).flatMap(
  ([, languages]) => languages,
);
