/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import type { EditorThemeClasses } from "lexical";

import "./ViewerTheme.css";

const theme: EditorThemeClasses = {
  autocomplete: "ViewerTheme__autocomplete",
  blockCursor: "ViewerTheme__blockCursor",
  characterLimit: "ViewerTheme__characterLimit",
  code: "ViewerTheme__code",
  codeHighlight: {
    atrule: "ViewerTheme__tokenAttr",
    attr: "ViewerTheme__tokenAttr",
    boolean: "ViewerTheme__tokenProperty",
    builtin: "ViewerTheme__tokenSelector",
    cdata: "ViewerTheme__tokenComment",
    char: "ViewerTheme__tokenSelector",
    class: "ViewerTheme__tokenFunction",
    "class-name": "ViewerTheme__tokenFunction",
    comment: "ViewerTheme__tokenComment",
    constant: "ViewerTheme__tokenProperty",
    deleted: "ViewerTheme__tokenDeleted",
    doctype: "ViewerTheme__tokenComment",
    entity: "ViewerTheme__tokenOperator",
    function: "ViewerTheme__tokenFunction",
    important: "ViewerTheme__tokenVariable",
    inserted: "ViewerTheme__tokenInserted",
    keyword: "ViewerTheme__tokenAttr",
    namespace: "ViewerTheme__tokenVariable",
    number: "ViewerTheme__tokenProperty",
    operator: "ViewerTheme__tokenOperator",
    prolog: "ViewerTheme__tokenComment",
    property: "ViewerTheme__tokenProperty",
    punctuation: "ViewerTheme__tokenPunctuation",
    regex: "ViewerTheme__tokenVariable",
    selector: "ViewerTheme__tokenSelector",
    string: "ViewerTheme__tokenSelector",
    symbol: "ViewerTheme__tokenProperty",
    tag: "ViewerTheme__tokenProperty",
    unchanged: "ViewerTheme__tokenUnchanged",
    url: "ViewerTheme__tokenOperator",
    variable: "ViewerTheme__tokenVariable",
  },
  embedBlock: {
    base: "ViewerTheme__embedBlock",
    focus: "ViewerTheme__embedBlockFocus",
  },
  hashtag: "ViewerTheme__hashtag",
  heading: {
    h1: "ViewerTheme__h1",
    h2: "ViewerTheme__h2",
    h3: "ViewerTheme__h3",
    h4: "ViewerTheme__h4",
    h5: "ViewerTheme__h5",
    h6: "ViewerTheme__h6",
  },
  hr: "ViewerTheme__hr",
  hrSelected: "ViewerTheme__hrSelected",
  image: "editor-image",
  indent: "ViewerTheme__indent",
  layoutContainer: "ViewerTheme__layoutContainer",
  layoutItem: "ViewerTheme__layoutItem",
  link: "ViewerTheme__link",
  list: {
    checklist: "ViewerTheme__checklist",
    listitem: "ViewerTheme__listItem",
    listitemChecked: "ViewerTheme__listItemChecked",
    listitemUnchecked: "ViewerTheme__listItemUnchecked",
    nested: {
      listitem: "ViewerTheme__nestedListItem",
    },
    olDepth: [
      "ViewerTheme__ol1",
      "ViewerTheme__ol2",
      "ViewerTheme__ol3",
      "ViewerTheme__ol4",
      "ViewerTheme__ol5",
    ],
    ul: "ViewerTheme__ul",
  },
  mark: "ViewerTheme__mark",
  markOverlap: "ViewerTheme__markOverlap",
  paragraph: "ViewerTheme__paragraph",
  quote: "ViewerTheme__quote",
  specialText: "ViewerTheme__specialText",
  tab: "ViewerTheme__tabNode",
  table: "ViewerTheme__table",
  tableAddColumns: "ViewerTheme__tableAddColumns",
  tableAddRows: "ViewerTheme__tableAddRows",
  tableAlignment: {
    center: "ViewerTheme__tableAlignmentCenter",
    right: "ViewerTheme__tableAlignmentRight",
  },
  tableCell: "ViewerTheme__tableCell",
  tableCellActionButton: "ViewerTheme__tableCellActionButton",
  tableCellActionButtonContainer: "ViewerTheme__tableCellActionButtonContainer",
  tableCellHeader: "ViewerTheme__tableCellHeader",
  tableCellResizer: "ViewerTheme__tableCellResizer",
  tableCellSelected: "ViewerTheme__tableCellSelected",
  tableFrozenColumn: "ViewerTheme__tableFrozenColumn",
  tableFrozenRow: "ViewerTheme__tableFrozenRow",
  tableRowStriping: "ViewerTheme__tableRowStriping",
  tableScrollableWrapper: "ViewerTheme__tableScrollableWrapper",
  tableSelected: "ViewerTheme__tableSelected",
  tableSelection: "ViewerTheme__tableSelection",
  text: {
    bold: "ViewerTheme__textBold",
    capitalize: "ViewerTheme__textCapitalize",
    code: "ViewerTheme__textCode",
    highlight: "ViewerTheme__textHighlight",
    italic: "ViewerTheme__textItalic",
    lowercase: "ViewerTheme__textLowercase",
    strikethrough: "ViewerTheme__textStrikethrough",
    subscript: "ViewerTheme__textSubscript",
    superscript: "ViewerTheme__textSuperscript",
    underline: "ViewerTheme__textUnderline",
    underlineStrikethrough: "ViewerTheme__textUnderlineStrikethrough",
    uppercase: "ViewerTheme__textUppercase",
  },
};

export default theme;
